blueprint:
  name: Motion Sensor Light Control
  description: >
     Motion Sensor Light Control via on off and delay and finally restore the previous light states.
  domain: automation
  source_url: https://github.com/carlosCastro99/motion_lights/blob/main/motion_lights.yaml
  input:
    activated:
        name: Activated
        description: "Toggle to activate or deactivate."
        selector:
            entity:
    target_lights:
        name: Lights
        description: "Lights to be used"
        selector:
          target:
            entity:
              domain: light
    delay:
      name: (OPTIONAL) Delay
      description: "Delay on/off lights"
      default: 1000
      selector:
        number:
          min: 0
          max: 20000
          unit_of_measurement: milliseconds

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input activated
    to: 'on'

variables:
  activated: !input activated
  delay: !input delay
  target_lights: !input target_lights

condition: []

action:
  - service: scene.create
    data:
        scene_id: all_lights_snapshot
        snapshot_entities: >
               {% set lights = states.light
                 | map(attribute='entity_id') | join(',') %}
                 {{lights}}
  - service: light.turn_on
    target: !input target_lights
    data:
      transition: 2
      kelvin: 6500
      brightness_pct: 20
  - repeat:
      while:
      - condition: template
        value_template: "{{ activated == none or is_state(activated, 'on') }}"
      sequence:
      - delay: 
          milliseconds: "{{ delay }}"
      - service: light.toggle
        target: !input target_lights
  - service: scene.turn_on
    data:
      entity_id: scene.all_lights_snapshot